development:
  password: ""
  theme_id: ""
  store: your-development-store.myshopify.com
  directory: .
  ignore_files:
    - config/settings_data.json
    - "*.md"
    - "*.txt"
    - "*.log"
    - ".git"
    - ".gitignore"
    - "node_modules"
    - "*.backup"
    - "*.tmp"

staging:
  password: ""
  theme_id: ""
  store: your-staging-store.myshopify.com
  directory: .
  ignore_files:
    - config/settings_data.json
    - "*.md"
    - "*.txt"
    - "*.log"
    - ".git"
    - ".gitignore"
    - "node_modules"
    - "*.backup"
    - "*.tmp"

production:
  password: ""
  theme_id: ""
  store: your-store.myshopify.com
  directory: .
  ignore_files:
    - config/settings_data.json
    - "*.md"
    - "*.txt"
    - "*.log"
    - ".git"
    - ".gitignore"
    - "node_modules"
    - "*.backup"
    - "*.tmp"
    - "*.dev.*"
    - "*.test.*"